# Standards: 0.1
---
- name: Kill microsoft-office
  loop: "{{ microsoft_office_apps }}"
  command: "killall {{ item }}"
  register: microsoft_office_kill
  failed_when: microsoft_office_kill.rc != 0 and "No matching processes belonging to you were found" not in microsoft_office_kill.stderr
  become: "{{ (microsoft_office_user != ansible_user_id) | bool }}"
  become_user: "{{ microsoft_office_user }}"

- name: Start microsoft-office
  loop: "{{ microsoft_office_apps }}"
  when: microsoft_office_started
  command: "open -g /Applications/{{ item }}.app"
  become: "{{ (microsoft_office_user != ansible_user_id) | bool }}"
  become_user: "{{ microsoft_office_user }}"

...
